apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cornell-notes

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # Uncomment for ingress
  # - ingress.yaml

commonLabels:
  app.kubernetes.io/name: cornell-notes
  app.kubernetes.io/version: "3.0.0"
