apiVersion: v1
kind: Service
metadata:
  name: cornell-notes
  namespace: cornell-notes
  labels:
    app: cornell-notes
spec:
  type: ClusterIP
  selector:
    app: cornell-notes
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
